export const FETCH_LAPSE = "LAPSE"
export const DELETE_LAPSE = "DELETE_LAPSE"
export const CLEAR_LAPSE = "CLEAR_LAPSE"

export const FETCH_LAPSE_SUCCESS = "FETCH_LAPSE_SUCCESS"
export const DELETE_LAPSE_SUCCESS = "DELETE_LAPSE_SUCCESS"
export const CLEAR_LAPSE_SUCCESS = "CLEAR_LAPSE_SUCCESS"

export const FETCH_LAPSE_SUCCESS_STATUS = "FETCH_LAPSE_SUCCESS_STATUS"
export const FETCH_LAPSE_START_STATUS = "FETCH_LAPSE_START_STATUS"
export const DELETE_LAPSE_SUCCESS_STATUS = "DELETE_LAPSE_SUCCESS_STATUS"
export const DELETE_LAPSE_START_STATUS = "DELETE_LAPSE_START_STATUS"
export const DELETE_LAPSE_FAIL_STATUS = "DELETE_LAPSE_FAIL_STATUS"

export const SET_API_URL_SUCCESS = "SET_API_URL_SUCCESS"
export const SET_API_KEY_SUCCESS = "SET_API_KEY_SUCCESS"
export const SET_API_SUCCESS = "SET_API_SUCCESS"
export const SET_API_URL = "SET_API_URL"
export const SET_API_KEY = "SET_API_KEY"
export const SET_API = "SET_API"
export const SET_API_TO_STATE = "SET_API_TO_STATE"

export const ENDPOINT_ERROR = "ENDPOINT_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"
